### ISSUE TITLE
Ship v3.0.0

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#112]
This Issue is to track progress of releasing **main.css** v3.0.0 🚢

## Release Notes

- Rename `sr-only' class to `visually-hidden` #109  (this is a breaking change so that's why version is bumped to v3)
- Remove print `thead` rule #101
- Remove Vendor-prefixed `::selection` #93
- Lots of dev dependency and npm publishing updates

## Todo List

- [x] Change 'master' to 'main' as default branch name (@roblarsen)
- [x] Update CHANGELOG.md (@coliff)
- [x] Publish update GitHub/npm (@roblarsen)

**Comment by roblarsen** [comment]
👍

**Comment by roblarsen** [comment]
@coliff OMG I'm back in here! I added an action to update the dist directory on pushes to main.

**Comment by coliff** [comment]
nice work on that update-the-dist bot! I'm going to open a PR to update Stylelint to v14. It's a major new version and can include breaking changes in some instances and may need some stylelint config changes. It's important we do this because he popular Stylelint extension for VS Code now only supports v14 and later.

**Comment by roblarsen** [comment]
@coliff Anything else? I can cut this release today and move the new version into the main project

**Comment by coliff** [comment]
yep - one last thing! Just found that our https://browserl.ist/?q=%22%3E+0.5%25%22%2C%22last+2+versions%22%2C%22Firefox+ESR%22%2C%22not+dead%22%2C%22IE+11%22 link is broken - maybe we could use a custom https://browserslist.dev URL instead?

**Comment by coliff** [comment]
not sure - but this looks good:
https://browserslist.dev/?q=PiAwLjUlLCBsYXN0IDIgdmVyc2lvbnMsIEZpcmVmb3ggRVNSLCBub3QgZGVhZCwgSUUgMTE%3D

**Comment by roblarsen** [comment]
Looks good to me!
