### ISSUE TITLE
Ship v2.0.0

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#28]
This issue is to track progress of releasing the first update to main.css! 🚢 

**Release Notes**

- Add `.stylelintrc` config ([#18](https://github.com/h5bp/main.css/pull/18))
- Rename `visuallyhidden` to `sr-only` ([#27](https://github.com/h5bp/main.css/pull/27))
- Fix broken link to 'printing tables' page ([#20](https://github.com/h5bp/main.css/pull/20))
- Alphabetize properties ([#20](https://github.com/h5bp/main.css/pull/15))
- Add `stylelint-config-recommended` to `package.json`
- Add `CONTRIBUTORS.md`([#9](https://github.com/h5bp/main.css/pull/9))
- Minor devdeps and README updates ([#11](https://github.com/h5bp/main.css/pull/11)), ([#24](https://github.com/h5bp/main.css/pull/24))

**Todo List**

- [x] Deal with currently open PRs
- [x] Update `CHANGELOG.md`
- [x] Publish v2.0.0 on GitHub (@roblarsen) 
- [x] Publish v2.0.0 on NPM (@roblarsen)

**Comment by roblarsen** [comment]
Anything else for this version? Time to update the changelog and release this, if there's nothing else.

**Comment by roblarsen** [comment]
closed via #30
